============================= test session starts ==============================
platform linux -- Python 3.10.10, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/seuronao/Documents/Is Prime-04-24-2023-04-50-47/JoaoGAO
collected 26 items

test_main.py ....F.....................                                  [100%]

=================================== FAILURES ===================================
______________________________ test_not_prime[1] _______________________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f2cb17b41c0>
test_input = '1'

    @pytest.mark.parametrize(
        "test_input", ["1", "4", "6", "8", "9", "10",
                       "12", "14", "15", "16", "18", "20"],
    )
    def test_not_prime(monkeypatch: MonkeyPatch, test_input: list[str]):
        mocked_input = lambda prompt="": test_input
    
        mocked_stdout = io.StringIO()
    
        with monkeypatch.context() as m:
            m.setattr(builtins, "input", mocked_input)
            m.setattr(sys, "stdout", mocked_stdout)
    
            sys.modules.pop("main", None)
            importlib.import_module(name="main", package="files")
    
        assert "Número inválido" not in mocked_stdout.getvalue().strip()
>       assert "Primo" not in mocked_stdout.getvalue().strip()
E       AssertionError: assert 'Primo' not in 'Primo'
E         'Primo' is contained here:
E           Primo

test_main.py:47: AssertionError
=========================== short test summary info ============================
FAILED test_main.py::test_not_prime[1] - AssertionError: assert 'Primo' not i...
========================= 1 failed, 25 passed in 0.06s =========================
